//! Differential expectations are generated by the pinned Pi code, not Rust.
use bashkitten::{agent::*, recovery};
use serde_json::{Value, json};

fn normalize_numbers(value: Value) -> Value {
    match value {
        Value::Number(number) => json!(number.as_f64().unwrap()),
        Value::Array(values) => Value::Array(values.into_iter().map(normalize_numbers).collect()),
        Value::Object(values) => Value::Object(
            values
                .into_iter()
                .map(|(key, value)| (key, normalize_numbers(value)))
                .collect(),
        ),
        value => value,
    }
}
macro_rules! assert_same {
    ($left:expr, $right:expr $(, $($message:tt)*)?) => {
        assert_eq!(normalize_numbers(json!($left)), normalize_numbers(json!($right)) $(, $($message)*)?);
    }
}

#[test]
fn pinned_pi_compaction_preparation_prompts_context_usage_and_recovery() {
    let fixtures: Value =
        serde_json::from_str(include_str!("fixtures/pi-compaction.json")).unwrap();
    assert_same!(fixtures["pin"], "9841914c71a74d81abe07f751aefd271fd924e63");
    for case in fixtures["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let entries: Vec<SessionEntry> = serde_json::from_value(case["entries"].clone()).unwrap();
        let settings: CompactionSettings =
            serde_json::from_value(case["settings"].clone()).unwrap();
        let messages = build_session_context(&entries, None);
        assert_same!(
            serde_json::to_value(&messages).unwrap(),
            case["messages"],
            "{name}: context"
        );
        let estimate = estimate_context_tokens(&messages);
        assert_same!(
            json!({"tokens":estimate.tokens,"usageTokens":estimate.usage_tokens,"trailingTokens":estimate.trailing_tokens,"lastUsageIndex":estimate.last_usage_index}),
            case["estimate"],
            "{name}: token estimate"
        );
        let cut = find_cut_point(&entries, 0, entries.len(), 20);
        assert_same!(
            json!({"firstKeptEntryIndex":cut.first_kept_entry_index,"turnStartIndex":cut.turn_start_index.map(|n| n as i64).unwrap_or(-1),"isSplitTurn":cut.is_split_turn}),
            case["cut"],
            "{name}: cut point"
        );
        let Some(preparation) = prepare_compaction(&entries, settings) else {
            assert!(case["preparation"].is_null(), "{name}: unexpectedly empty");
            continue;
        };
        let expected = &case["preparation"];
        assert_same!(
            preparation.first_kept_entry_id,
            expected["firstKeptEntryId"].as_str().unwrap(),
            "{name}: retained ID"
        );
        assert_same!(
            preparation.tokens_before,
            expected["tokensBefore"].as_u64().unwrap(),
            "{name}: tokens before"
        );
        assert_same!(
            json!(preparation.messages_to_summarize),
            expected["messagesToSummarize"],
            "{name}: summarized messages"
        );
        assert_same!(
            json!(preparation.turn_prefix_messages),
            expected["turnPrefixMessages"],
            "{name}: prefix messages"
        );
        assert_same!(
            json!(preparation.previous_summary),
            expected["previousSummary"],
            "{name}: previous summary"
        );
        let details = compute_file_lists(&preparation.file_operations);
        assert_same!(
            json!(details),
            case["result"]["details"],
            "{name}: file tracking"
        );
        let mut requests = Vec::new();
        let split = preparation.is_split_turn && !preparation.turn_prefix_messages.is_empty();
        if !split || !preparation.messages_to_summarize.is_empty() {
            requests.push((
                build_summarization_prompt(
                    &preparation.messages_to_summarize,
                    preparation.previous_summary.as_deref(),
                    Some("preserve tests"),
                ),
                summary_max_tokens(settings.reserve_tokens, 1000),
            ));
        }
        if split {
            requests.push((
                build_turn_prefix_prompt(&preparation.turn_prefix_messages),
                turn_prefix_max_tokens(settings.reserve_tokens, 1000),
            ));
        }
        assert_same!(
            requests.len(),
            case["requests"].as_array().unwrap().len(),
            "{name}: summary count"
        );
        for ((prompt, max_tokens), expected) in
            requests.iter().zip(case["requests"].as_array().unwrap())
        {
            assert_same!(
                SUMMARIZATION_SYSTEM_PROMPT,
                expected["systemPrompt"],
                "{name}: summary system prompt"
            );
            assert_same!(
                json!([{"role":"user","content":[{"type":"text","text":prompt}]}]),
                expected["messages"],
                "{name}: summary prompt"
            );
            assert_same!(
                json!(max_tokens),
                expected["options"]["maxTokens"],
                "{name}: budget"
            );
        }
        let summary = if split {
            merge_split_turn_summary(
                (requests.len() == 2).then_some("summary 1"),
                &format!("summary {}", requests.len()),
            )
        } else {
            "summary 1".to_owned()
        } + &format_file_operations(&details);
        assert_same!(summary, case["result"]["summary"], "{name}: final summary");
        let usage: Usage = serde_json::from_value(fixtures["summaryUsage"].clone()).unwrap();
        let usage = if requests.len() == 2 {
            combine_usage(&usage, &usage)
        } else {
            usage
        };
        assert_same!(
            json!(usage),
            case["result"]["usage"],
            "{name}: summary usage"
        );
    }
    for case in fixtures["recovery"].as_array().unwrap() {
        let message: AgentMessage = serde_json::from_value(case["message"].clone()).unwrap();
        assert_same!(
            json!(recovery::is_retryable(&message)),
            case["retryable"],
            "retry: {}",
            case["message"]["errorMessage"]
        );
        assert_same!(
            json!(recovery::is_overflow(&message, 2000)),
            case["overflow"],
            "overflow: {}",
            case["message"]["errorMessage"]
        );
    }
    for case in fixtures["usageCases"].as_array().unwrap() {
        let entries: Vec<SessionEntry> = serde_json::from_value(case["entries"].clone()).unwrap();
        let context = build_session_context(&entries, None);
        let snapshot = bashkitten::usage::snapshot(
            &entries,
            &context,
            UsageTotals::default(),
            case["contextWindow"].as_u64().unwrap(),
            case["subscription"].as_bool().unwrap(),
            case["auto"].as_bool().unwrap(),
        );
        assert_same!(snapshot.text, case["text"], "{}: Pi footer", case["name"]);
    }
    for case in fixtures["fixedCases"].as_array().unwrap() {
        assert_same!(
            bashkitten::usage::fixed(
                case["value"].as_f64().unwrap(),
                case["digits"].as_u64().unwrap() as u32
            ),
            case["text"],
            "Pi toFixed: {case}"
        );
    }
    for case in fixtures["tokenCases"].as_array().unwrap() {
        assert_same!(
            bashkitten::usage::format_tokens(case["value"].as_u64().unwrap()),
            case["text"],
            "Pi token label: {case}"
        );
    }
}
