// Exercise Pi's actual agent loop and provider parser through deterministic fetch.
import {execFileSync} from 'node:child_process';import {writeFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
const root=process.env.PI_REFERENCE!;const pin='9841914c71a74d81abe07f751aefd271fd924e63';if(execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==pin)throw Error('Wrong pin');globalThis.fetch=async()=>{throw Error('No network');};
const {agentLoop}=await import(pathToFileURL(`${root}/packages/agent/src/agent-loop.ts`).href);const {stream}=await import(pathToFileURL(`${root}/packages/ai/src/api/openai-completions.ts`).href);
const chunks=[{choices:[{delta:{tool_calls:[{index:0,id:'cut-write',function:{name:'write',arguments:'{"path":"blocked.txt","content":"blocked"}'}},{index:1,id:'cut-read',function:{name:'read',arguments:'{"path":"other.txt"}'}}]},finish_reason:'length'}]}, {choices:[{delta:{tool_calls:[{index:0,id:'repair-write',function:{name:'write',arguments:'{"path":"recovered.txt","content":"recovered'}}]},finish_reason:'tool_calls'}]}, {choices:[{delta:{content:'done'},finish_reason:'stop'}]}];
const model={id:'model',name:'Fixture',provider:'fixture',api:'openai-completions',baseUrl:'http://localhost/v1',reasoning:false,input:['text'],contextWindow:128000,maxTokens:1000,cost:{input:0,output:0,cacheRead:0,cacheWrite:0}};
const executed:any[]=[];const requests:any[]=[];const events:any[]=[];
const tools=['write','read'].map(name=>({name,label:name,description:name,parameters:{type:'object',properties:{path:{type:'string'},content:{type:'string'}},required:['path']},execute:async(id:any,args:any)=>{executed.push({id,name,args});return {content:[{type:'text',text:name==='write'?`Successfully wrote to ${args.path}`:'read'}]};}}));
let index=0;
const loop=agentLoop([{role:'user',content:'test',timestamp:0}],{systemPrompt:'System',messages:[],tools},{model,convertToLlm:(m:any)=>m},undefined,(model:any,context:any,options:any)=>stream(model,context,{...options,apiKey:'fixture-key',fetch:async(_:any,init:any)=>{requests.push(JSON.parse(init.body));return new Response(`data: ${JSON.stringify(chunks[index++])}\n\ndata: [DONE]\n\n`,{headers:{'content-type':'text/event-stream'}});}}));
for await(const event of loop)events.push({type:event.type,...event.toolCallId?{toolCallId:event.toolCallId}:{}});
const messages=(await loop.result()).map((message:any)=>{delete message.timestamp;return message;});writeFileSync(process.argv[2],JSON.stringify({pin,chunks,messages,events,requests,executed},null,2)+'\n');console.log(`Captured actual Pi truncated-call recovery: ${requests.length} provider requests, ${executed.length} tool executed.`);
