// Full pinned Codex SSE stream oracle, entirely offline.
import {execFileSync} from 'node:child_process';import {writeFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
const root=process.env.PI_REFERENCE!;const pin='9841914c71a74d81abe07f751aefd271fd924e63';if(execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==pin)throw Error('Wrong pin');
globalThis.fetch=async()=>{throw Error('No network');};const {stream}=await import(pathToFileURL(`${root}/packages/ai/src/api/openai-codex-responses.ts`).href);
const token='e30.'+Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'fixture-account'}})).toString('base64url')+'.fixture';
const base={id:'gpt-5.5',name:'Fixture',api:'openai-codex-responses',provider:'openai-codex',baseUrl:'http://localhost/backend-api',contextWindow:272000,maxTokens:128000,reasoning:true,input:['text','image'],cost:{input:1,output:2,cacheRead:.1,cacheWrite:1.25}};
const cases:any[]=[];const done=(extra:any={})=>({type:'response.completed',response:{id:'terminal',status:'completed',output:[],...extra}});const item=(type:string,id:string,extra:any={})=>({type,id,...extra});
const text=item('message','msg_1',{phase:'final_answer',role:'assistant',content:[{type:'output_text',text:'Answer',annotations:[]}]});
const thought=item('reasoning','rs_1',{summary:[{type:'summary_text',text:'Summary'}],encrypted_content:'opaque'});
const call=item('function_call','fc_1',{call_id:'call1',name:'read',arguments:'{"path":"a"}'});
const added=(item:any,index=0)=>({type:'response.output_item.added',output_index:index,item});const ended=(item:any,index=0)=>({type:'response.output_item.done',output_index:index,item});
async function add(name:string,chunks:any[],extra:any={},payload?:string,options:any={}){const model={...base,...extra};const body=payload??chunks.map(v=>'data: '+JSON.stringify(v)+'\n\n').join('');const events:any[]=[];const result=stream(model,{messages:[]},{...options,apiKey:token,transport:'sse',fetch:async()=>new Response(body,{headers:{'content-type':'text/event-stream'}})});for await(const event of result){events.push({type:event.type,index:event.contentIndex,delta:event.delta});}const expected=await result.result();delete expected.timestamp;cases.push({name,model,chunks,payload,options,events,expected});}
await add('empty',[]);await add('done-only',[],{},'data: [DONE]\n\n');
for(const status of [undefined,'completed','incomplete','failed','cancelled','queued','in_progress','unknown'])for(const reason of [undefined,'max_output_tokens','content_filter'])await add(`status-${status}-${reason}`,[done({status,incomplete_details:reason?{reason}:undefined,end_turn:false})]);
await add('created-and-terminal-id',[{type:'response.created',response:{id:'initial'}},ended(text),done()]);
await add('ignored-deltas-without-start',[{type:'response.output_text.delta',output_index:0,delta:'ignored'},{type:'response.reasoning_text.delta',output_index:1,delta:'ignored'},done()]);
await add('tool-literal-surrogate',[added({...call,arguments:''}),{type:'response.function_call_arguments.delta',output_index:0,delta:'{"path":"\ud83d'},done()]);
await add('tool-split-surrogate',[added({...call,arguments:''}),{type:'response.function_call_arguments.delta',output_index:0,delta:'{"path":"\ud83d'},{type:'response.function_call_arguments.delta',output_index:0,delta:'\ude00"}'},ended({...call,arguments:''}),done()]);
await add('text-split-surrogate' ,[added(text),{type:'response.output_text.delta',output_index:0,delta:'\ud83d'},{type:'response.output_text.delta',output_index:0,delta:'\ude00'},done()]);
await add('thinking-split-surrogate',[added(thought),{type:'response.reasoning_text.delta',output_index:0,delta:'\ud83d'},{type:'response.reasoning_text.delta',output_index:0,delta:'\ude00'},done()]);
await add('text-empty-start' ,[added(text),done()]);await add('text-delta-done',[added(text),{type:'response.output_text.delta',output_index:0,delta:'partial'},ended(text),done()]);
await add('reasoning-summary-final',[added(thought),{type:'response.reasoning_summary_text.delta',output_index:0,delta:'Partial'},{type:'response.reasoning_summary_part.done',output_index:0},ended(thought),ended(text,1),done()]);
await add('reasoning-content-final',[added(thought),ended({...thought,summary:[],content:[{type:'reasoning_text',text:'Full reasoning'}]}),done()]);
await add('reasoning-partial-retained',[added(thought),{type:'response.reasoning_text.delta',output_index:0,delta:'retain'},ended({...thought,summary:[],encrypted_content:undefined}),done()]);
await add('reasoning-backfill',[ended({...thought,encrypted_content:undefined},7),done({output:[thought]})]);
await add('reasoning-terminal-only',[done({output:[thought]})]);
await add('duplicate-index',[ended(text,1),ended({...text,id:'msg_2',content:[{type:'output_text',text:'Second'}]},1),done()]);
await add('out-of-order-index',[added(thought,7),added(text,0),ended(text,0),ended(thought,7),done()]);
await add('refusal',[added(text),{type:'response.refusal.delta',output_index:0,delta:'No'},ended({...text,content:[{type:'refusal',refusal:'Declined'}]}),done()]);
await add('tool-initial-args',[added(call),done()]);await add('tool-delta',[added({...call,arguments:''}),{type:'response.function_call_arguments.delta',output_index:0,delta:'{"path":"b'},{type:'response.function_call_arguments.done',output_index:0,arguments:'{"path":"bee"}'},ended({...call,arguments:'',namespace:'functions'}),done()]);
await add('tool-final-replacement',[added(call),{type:'response.function_call_arguments.done',output_index:0,arguments:'{"path":"replacement"}'},ended({...call,id:'fc_changed',call_id:'changed',name:'changed',arguments:''}),done()]);
await add('tool-same-ids',[ended({...call,id:'same',call_id:'same'}),done()]);
await add('tool-partial-json',[ended({...call,arguments:'{"path":"unfinished'}),done()]);
await add('custom-tool',[added(item('custom_tool_call','ctc_1',{call_id:'call1',name:'read',input:'first'})),{type:'response.custom_tool_call_input.delta',output_index:0,delta:'\nnext'},{type:'response.custom_tool_call_input.done',output_index:0,input:'replaced'},ended(item('custom_tool_call','ctc_1',{call_id:'call1',name:'read',input:'final',namespace:'functions'})),done()]);
const custom=item('custom_tool_call','ctc_1',{call_id:'call1',name:'read',input:'first'});
await add('custom-monotonic',[added(custom),{type:'response.custom_tool_call_input.delta',output_index:0,delta:'\\nnext'},{type:'response.custom_tool_call_input.done',output_index:0,input:'first\\nnext'},ended({...custom,input:'first\\nnext'}),done()]);
await add('custom-pending',[added(custom),done()]);
await add('custom-closed-pending',[added(custom),{type:'response.custom_tool_call_input.done',output_index:0,input:'first'},done()]);
await add('custom-change-after-close',[added(custom),{type:'response.custom_tool_call_input.done',output_index:0,input:'first'},{type:'response.custom_tool_call_input.delta',output_index:0,delta:'extra'},done()]);
await add('partial-no-terminal',[added(thought),{type:'response.reasoning_text.delta',output_index:0,delta:'Partial'},added({...call,arguments:''},1),{type:'response.function_call_arguments.delta',output_index:1,delta:'{"path":"a'}]);
for(const event of [{type:'error',message:'Top error',code:'top'},{type:'error',error:{code:'nested',message:'Nested error'}},{type:'error',code:'code-only'},{type:'error',extra:1},{type:'response.failed',response:{error:{code:'bad',message:'Failed response'}}},{type:'response.failed',response:{}}])await add(`error-${cases.length}`,[ended(text),event]);
for(const usage of [{input_tokens:100,output_tokens:20,total_tokens:333},{input_tokens:100,output_tokens:20},{input_tokens:10,output_tokens:2,input_tokens_details:{cached_tokens:20,cache_write_tokens:5},output_tokens_details:{reasoning_tokens:0}},{input_tokens:100,output_tokens:20,input_tokens_details:{cached_tokens:30,cache_write_tokens:5},output_tokens_details:{reasoning_tokens:7},total_tokens:120}])for(const service_tier of ['default','priority','flex'])await add(`usage-${cases.length}-${service_tier}`,[done({usage,service_tier})]);
for(const serviceTier of ['auto','priority','flex'])for(const service_tier of [undefined,'default','priority','flex','unknown'])for(const id of ['gpt-5.5','gpt-5.6-luna'])await add(`tier-${id}-${serviceTier}-${service_tier}`,[done({service_tier,usage:{input_tokens:100,output_tokens:20,total_tokens:120}})],{id},undefined,{serviceTier});
await add('event-line-not-type',[],{},'event: response.output_item.done\ndata: '+JSON.stringify({output_index:0,item:text})+'\n\ndata: '+JSON.stringify(done())+'\n\n');
await add('done-before-terminal',[],{},'data: [DONE]\n\ndata: '+JSON.stringify(done())+'\n\n');
await add('residual-frame',[],{},'data: '+JSON.stringify(done()));
writeFileSync(process.argv[2],JSON.stringify({pin,token,cases},null,2)+'\n');console.log(`Captured ${cases.length} complete Codex SSE cases.`);
