// Offline Pi SDK HTTP error, affinity and retry oracle; no outbound requests.
import {execFileSync} from 'node:child_process';import {writeFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
const root=process.env.PI_REFERENCE!;const pin='9841914c71a74d81abe07f751aefd271fd924e63';if(execFileSync('git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).trim()!==pin)throw Error('Wrong Pi commit');
globalThis.fetch=async()=>{throw Error('No network');};
const {stream}=await import(pathToFileURL(`${root}/packages/ai/src/api/openai-completions.ts`).href);
const model={id:'fixture',name:'Fixture',api:'openai-completions',provider:'fixture',baseUrl:'http://localhost/v1',contextWindow:128000,maxTokens:1000,reasoning:false,input:['text'],cost:{input:0,output:0,cacheRead:0,cacheWrite:0}};
const cases:any[]=[];const ok={status:200,body:'data: {"choices":[{"delta":{"content":"ok"},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n'};
async function add(name:string,responses:any[],options:any={},extra:any={}){const requests:any[]=[];const result=stream({...model,...extra},{messages:[{role:'user',content:'test',timestamp:0}]},{apiKey:'fixture-key',sessionId:'session-'+ 'x'.repeat(80),maxRetries:0,...options,fetch:async(url:any,init:any)=>{requests.push({url,headers:Object.fromEntries(new Headers(init.headers)),body:JSON.parse(init.body)});const response=responses[Math.min(requests.length-1,responses.length-1)];return new Response(response.body,{status:response.status,headers:{'content-type':response.status===200?'text/event-stream':'application/json',...response.headers}});}});for await(const _ of result){}const message=await result.result();cases.push({name,responses,options,model:{...model,...extra},requests,expectedError:message.errorMessage??null,expectedStop:message.stopReason});}
for(const [status,body] of [[400,JSON.stringify({error:{message:'bad input',type:'invalid_request_error',param:'messages'}})],[429,JSON.stringify({error:{message:'Quota exhausted',code:'insufficient_quota'}})],[503,'upstream unavailable'],[401,''],[422,JSON.stringify({detail:'Invalid',message:'Top level error'})],[400,JSON.stringify({error:'plain string'})],[400,JSON.stringify({error:{message:{field:'bad'}}})],[500,JSON.stringify({error:{message:'  preserve\nspaces  '}})],[400,JSON.stringify({error:{message:'x'.repeat(5000)}})],[502,JSON.stringify({error:{message:'Provider returned error',metadata:{raw:'Upstream detail'}}})]])await add(`http-${status}-${cases.length}`,[{status,body}]);
for(const status of [400,408,409,429,500,503])await add(`retry-${status}`,[{status,body:'temporary',headers:{'retry-after-ms':'0'}},ok],{maxRetries:2});
await add('retry-disabled-header',[{status:503,body:'no retry',headers:{'x-should-retry':'false'}},ok],{maxRetries:2});
await add('retry-enabled-header',[{status:400,body:'retry',headers:{'x-should-retry':'true','retry-after':'0'}},ok],{maxRetries:2});
await add('retry-limit',[{status:503,body:'overloaded',headers:{'retry-after-ms':'0'}}],{maxRetries:2});
await add('retry-delay-cap',[{status:429,body:'wait',headers:{'retry-after-ms':'61000'}}],{maxRetries:1});
for(const format of ['openai','openrouter','generic'])await add(`affinity-${format}`,[ok],{},{compat:{sendSessionAffinityHeaders:true,sessionAffinityFormat:format}});
await add('affinity-no-cache',[ok],{cacheRetention:'none'},{compat:{sendSessionAffinityHeaders:true}});
await add('options-headers-last',[ok],{headers:{Authorization:'Bearer replacement',session_id:'replacement-session','x-session-affinity':'replacement-affinity','User-Agent':'fixture-agent'}},{headers:{'x-fixture':'model-default'},compat:{sendSessionAffinityHeaders:true}});
writeFileSync(process.argv[2],JSON.stringify({pin,cases},null,2)+'\n');console.log(`Captured ${cases.length} HTTP, retry and header cases without network.`);
