name: Linux packages
'on':
  workflow_dispatch:
    inputs:
      warm_gkrust:
        description: Warm the Rust compiler cache before Gecko
        default: false
        type: boolean
      auth_run:
        required: true
        type: string
      search_run:
        required: true
        type: string
  workflow_call:
    inputs:
      warm_gkrust:
        default: false
        type: boolean
      auth_run:
        required: true
        type: string
      search_run:
        required: true
        type: string
    secrets:
      BUILD_REPOS_TOKEN:
        required: true
permissions:
  contents: read
  actions: read
jobs:
  browser:
    strategy:
      fail-fast: false
      matrix:
        target:
        - linux-arm64
        - linux-amd64
    uses: ./.github/workflows/remote-browser.yml
    with:
      target: ${{ matrix.target }}
      warm_gkrust: ${{ inputs.warm_gkrust }}
      auth_run: ${{ inputs.auth_run }}
      search_run: ${{ inputs.search_run }}
    secrets:
      BUILD_REPOS_TOKEN: ${{ secrets.BUILD_REPOS_TOKEN }}
